name: Badges

on:
  schedule:
    - cron: '24 03 * * 3'
  workflow_dispatch:

permissions: {}

jobs:
  downloads:
    name: Docker pulls
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Get package downloads
        id: downloads
        uses: ./misc/action/package-downloads
        with:
          url: ${{ github.server_url }}
          repo: ${{ github.repository }}
          package: publish-unit-test-result-action

      - name: Create badge
        uses: emibcn/badge-action@808173dd03e2f30c980d03ee49e181626088eee8  # v2.0.3
        with:
          label: Docker pulls
          status: ${{ steps.downloads.outputs.total_downloads }} (${{ steps.downloads.outputs.recent_downloads_per_day }}/d)
          color: blue
          path: downloads.svg

      - name: Create JSON
        run: |
          echo '{"subject": "Docker pulls", "status": "${{ steps.downloads.outputs.total_downloads }} (${{ steps.downloads.outputs.recent_downloads_per_day }}/d)", "color": "blue"}' > downloads.json

      - name: Upload badge to Gist
        uses: andymckay/append-gist-action@ab30bf28df67017c7ad696500b218558c7c04db3  # v0.3
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/EnricoMi/612cb538c14731f1a8fefe504f519395
          file: downloads.svg

      - name: Upload JSON to Gist
        uses: andymckay/append-gist-action@ab30bf28df67017c7ad696500b218558c7c04db3  # v0.3
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/EnricoMi/612cb538c14731f1a8fefe504f519395
          file: downloads.json

  workflows:
    name: Dependent workflows
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Fetch workflows
        id: workflows
        uses: ./misc/action/fetch-workflows

      - name: Create badge
        uses: emibcn/badge-action@808173dd03e2f30c980d03ee49e181626088eee8  # v2.0.3
        with:
          label: GitHub Workflows
          status: ${{ steps.workflows.outputs.total_workflows }}
          color: blue
          path: workflows.svg

      - name: Create JSON
        run: |
          echo '{"subject": "GitHub Workflows", "status": "${{ steps.workflows.outputs.total_workflows }}", "color": "blue"}' > workflows.json

      - name: Upload badge to Gist
        uses: andymckay/append-gist-action@ab30bf28df67017c7ad696500b218558c7c04db3  # v0.3
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/EnricoMi/612cb538c14731f1a8fefe504f519395
          file: workflows.svg

      - name: Upload JSON to Gist
        uses: andymckay/append-gist-action@ab30bf28df67017c7ad696500b218558c7c04db3  # v0.3
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/EnricoMi/612cb538c14731f1a8fefe504f519395
          file: workflows.json
